In [19]:
import pandas as pd

In [20]:
df = pd.read_csv("students.csv")
df.head()

,student_id,name,gender,department,city,age,cgpa,attendance,study_hours,scholarship,tuition_fee
0,1,Ayesha Rahman,Female,CSE,Dhaka,21,3.92,95.0,25.0,Yes,65000
1,2,Karim Uddin,Male,EEE,Chattogram,22,3.45,80.0,15.0,No,70000
2,3,Sadia Islam,Female,CSE,Sylhet,20,3.78,88.0,22.0,Yes,65000
3,4,Tamim Hossain,Male,BBA,Dhaka,23,2.95,72.0,10.0,No,55000
4,5,Nabila Akter,Female,CSE,Rajshahi,21,3.66,90.0,20.0,Yes,65000

from an excel file

In [21]:
df = pd.read_excel("students.xlsx")

In [22]:
df = pd.read_csv ("students.csv",index_col="student_id")
df.head(3)

,name,gender,department,city,age,cgpa,attendance,study_hours,scholarship,tuition_fee
student_id,,,,,,,,,,
1,Ayesha Rahman,Female,CSE,Dhaka,21,3.92,95.0,25.0,Yes,65000
2,Karim Uddin,Male,EEE,Chattogram,22,3.45,80.0,15.0,No,70000
3,Sadia Islam,Female,CSE,Sylhet,20,3.78,88.0,22.0,Yes,65000

isapecting data-do this first,always

In [23]:
df.head()
df.tail(3)

,name,gender,department,city,age,cgpa,attendance,study_hours,scholarship,tuition_fee
student_id,,,,,,,,,,
28,Priya Das,Female,EEE,Rajshahi,21,3.48,83.0,17.0,No,70000
29,Tanvir Ahmed,Male,CSE,Dhaka,22,3.58,86.0,19.0,No,65000
30,Sanjida Islam,Female,Civil,Khulna,20,3.42,80.0,16.0,No,58000

In [24]:
#shape
print(df.shape)

(30, 10)

In [25]:
#colum name
print(df.columns)

Index(['name', 'gender', 'department', 'city', 'age', 'cgpa', 'attendance',
       'study_hours', 'scholarship', 'tuition_fee'],
      dtype='str')

Info()-a full summary:column names,how many non-missing values,and each typ.This is the fastest way to spot missing data

In [26]:
df.info

<bound method DataFrame.info of                       name  gender department        city  age  cgpa  \
student_id
1            Ayesha Rahman  Female        CSE       Dhaka   21  3.92
2              Karim Uddin    Male        EEE  Chattogram   22  3.45
3              Sadia Islam  Female        CSE      Sylhet   20  3.78
4            Tamim Hossain    Male        BBA       Dhaka   23  2.95
5             Nabila Akter  Female        CSE    Rajshahi   21  3.66
6                Rahim Mia    Male         ME      Khulna   22  3.10
7           Farhana Yasmin  Female        EEE       Dhaka   20  3.88
8               Imran Khan    Male        BBA  Chattogram   24  3.25
9            Sumaiya Begum  Female        CSE       Dhaka   19  3.99
10             Jahid Hasan    Male         ME      Sylhet   23  2.70
11          Mitu Chowdhury  Female        EEE    Rajshahi   21  3.55
12             Rifat Ahmed    Male        CSE  Chattogram   22  3.40
13           Lamia Sultana  Female        BBA       Dhaka   20  3.72
14          Shakib Al Amin    Male         ME      Khulna   24  3.05
15            Nusrat Jahan  Female        CSE       Dhaka   21  3.81
16              Fahim Reza    Male      Civil    Barishal   22  3.30
17             Tania Haque  Female        EEE      Sylhet   20  3.60
18            Sabbir Ahmed    Male        CSE       Dhaka   23   NaN
19             Rima Khatun  Female        BBA  Chattogram   21  3.50
20            Arif Hossain    Male         ME    Rajshahi   22   NaN
21           Sharmin Akter  Female        CSE      Khulna   20  3.95
22            Nayeem Islam    Male      Civil       Dhaka   23  3.20
23            Jarin Tasnim  Female        EEE       Dhaka   21  3.70
24             Rakib Hasan    Male        CSE      Sylhet   22  3.35
25            Mehedi Hasan    Male        BBA    Barishal   24  2.60
26            Ishrat Jahan  Female        CSE       Dhaka   20  3.85
27              Sohel Rana    Male         ME  Chattogram   23  3.00
28               Priya Das  Female        EEE    Rajshahi   21  3.48
29            Tanvir Ahmed    Male        CSE       Dhaka   22  3.58
30           Sanjida Islam  Female      Civil      Khulna   20  3.42

            attendance  study_hours scholarship  tuition_fee
student_id
1                 95.0         25.0         Yes        65000
2                 80.0         15.0          No        70000
3                 88.0         22.0         Yes        65000
4                 72.0         10.0          No        55000
5                 90.0         20.0         Yes        65000
6                 68.0         12.0          No        60000
7                 93.0         24.0         Yes        70000
8                 78.0         14.0          No        55000
9                 98.0         28.0         Yes        65000
10                65.0          8.0          No        60000
11                85.0         18.0          No        70000
12                82.0         16.0          No        65000
13                89.0         21.0         Yes        55000
14                70.0         11.0          No        60000
15                91.0         23.0         Yes        65000
16                76.0         13.0          No        58000
17                87.0         19.0          No        70000
18                66.0          9.0          No        65000
19                84.0         17.0          No        55000
20                71.0         12.0          No        60000
21                96.0         27.0         Yes        65000
22                74.0         13.0          No        58000
23                88.0         20.0         Yes        70000
24                79.0         15.0          No        65000
25                 NaN          7.0          No        55000
26                92.0         24.0         Yes        65000
27                69.0          NaN          No        60000
28                83.0         17.0          No        70000
29                86.0         19.0          No        65000
30                80.0         16.0          No        58000  >

Describe()- statistic for the number columns(count,mean,min,max,quartiles)

In [27]:
df.describe()

             age       cgpa  attendance  study_hours   tuition_fee
count  30.000000  28.000000   29.000000    29.000000     30.000000
mean   21.566667   3.455000   81.896552    17.068966  62800.000000
std     1.381736   0.371977    9.581771     5.725451   5175.539286
min    19.000000   2.600000   65.000000     7.000000  55000.000000
25%    20.250000   3.237500   74.000000    13.000000  58500.000000
50%    21.500000   3.490000   83.000000    17.000000  65000.000000
75%    22.750000   3.735000   89.000000    21.000000  65000.000000
max    24.000000   3.990000   98.000000    28.000000  70000.000000

Selecting columns

In [28]:
df["name"].head(3)

student_id
1    Ayesha Rahman
2      Karim Uddin
3      Sadia Islam
Name: name, dtype: str

In [29]:
df[["name","cgpa"]].head(5)

                     name  cgpa
student_id
1           Ayesha Rahman  3.92
2             Karim Uddin  3.45
3             Sadia Islam  3.78
4           Tamim Hossain  2.95
5            Nabila Akter  3.66

Selecting rows-loc and iloc

In [30]:
df.loc[0:2]
df.iloc[0:2]

,name,gender,department,city,age,cgpa,attendance,study_hours,scholarship,tuition_fee
student_id,,,,,,,,,,
1,Ayesha Rahman,Female,CSE,Dhaka,21,3.92,95.0,25.0,Yes,65000
2,Karim Uddin,Male,EEE,Chattogram,22,3.45,80.0,15.0,No,70000

In [31]:
df.iloc[0:5,1:3]

            gender department
student_id
1           Female        CSE
2             Male        EEE
3           Female        CSE
4             Male        BBA
5           Female        CSE

Filtering-the most useful skill

In [32]:
df[df["cgpa"]>3.2]

,name,gender,department,city,age,cgpa,attendance,study_hours,scholarship,tuition_fee
student_id,,,,,,,,,,
1,Ayesha Rahman,Female,CSE,Dhaka,21,3.92,95.0,25.0,Yes,65000
2,Karim Uddin,Male,EEE,Chattogram,22,3.45,80.0,15.0,No,70000
3,Sadia Islam,Female,CSE,Sylhet,20,3.78,88.0,22.0,Yes,65000
5,Nabila Akter,Female,CSE,Rajshahi,21,3.66,90.0,20.0,Yes,65000
7,Farhana Yasmin,Female,EEE,Dhaka,20,3.88,93.0,24.0,Yes,70000
8,Imran Khan,Male,BBA,Chattogram,24,3.25,78.0,14.0,No,55000
9,Sumaiya Begum,Female,CSE,Dhaka,19,3.99,98.0,28.0,Yes,65000
11,Mitu Chowdhury,Female,EEE,Rajshahi,21,3.55,85.0,18.0,No,70000
12,Rifat Ahmed,Male,CSE,Chattogram,22,3.40,82.0,16.0,No,65000
13,Lamia Sultana,Female,BBA,Dhaka,20,3.72,89.0,21.0,Yes,55000
15,Nusrat Jahan,Female,CSE,Dhaka,21,3.81,91.0,23.0,Yes,65000
16,Fahim Reza,Male,Civil,Barishal,22,3.30,76.0,13.0,No,58000
17,Tania Haque,Female,EEE,Sylhet,20,3.60,87.0,19.0,No,70000
19,Rima Khatun,Female,BBA,Chattogram,21,3.50,84.0,17.0,No,55000
21,Sharmin Akter,Female,CSE,Khulna,20,3.95,96.0,27.0,Yes,65000
23,Jarin Tasnim,Female,EEE,Dhaka,21,3.70,88.0,20.0,Yes,70000
24,Rakib Hasan,Male,CSE,Sylhet,22,3.35,79.0,15.0,No,65000
26,Ishrat Jahan,Female,CSE,Dhaka,20,3.85,92.0,24.0,Yes,65000
28,Priya Das,Female,EEE,Rajshahi,21,3.48,83.0,17.0,No,70000
29,Tanvir Ahmed,Male,CSE,Dhaka,22,3.58,86.0,19.0,No,65000
30,Sanjida Islam,Female,Civil,Khulna,20,3.42,80.0,16.0,No,58000

Two condition - use & for AND,| FOR Or.

In [33]:
df[(df["cgpa"]>3.8)&(df["department"]=="CSE")]

,name,gender,department,city,age,cgpa,attendance,study_hours,scholarship,tuition_fee
student_id,,,,,,,,,,
1,Ayesha Rahman,Female,CSE,Dhaka,21,3.92,95.0,25.0,Yes,65000
9,Sumaiya Begum,Female,CSE,Dhaka,19,3.99,98.0,28.0,Yes,65000
15,Nusrat Jahan,Female,CSE,Dhaka,21,3.81,91.0,23.0,Yes,65000
21,Sharmin Akter,Female,CSE,Khulna,20,3.95,96.0,27.0,Yes,65000
26,Ishrat Jahan,Female,CSE,Dhaka,20,3.85,92.0,24.0,Yes,65000

In [34]:
df[df["scholarship"] == "YES"].shape[0]

0

SORTING-sort_values orders rows by a column.
ascending=False for highest first

In [35]:
df.sort_values("cgpa",ascending=False).head(6)

,name,gender,department,city,age,cgpa,attendance,study_hours,scholarship,tuition_fee
student_id,,,,,,,,,,
9,Sumaiya Begum,Female,CSE,Dhaka,19,3.99,98.0,28.0,Yes,65000
21,Sharmin Akter,Female,CSE,Khulna,20,3.95,96.0,27.0,Yes,65000
1,Ayesha Rahman,Female,CSE,Dhaka,21,3.92,95.0,25.0,Yes,65000
7,Farhana Yasmin,Female,EEE,Dhaka,20,3.88,93.0,24.0,Yes,70000
26,Ishrat Jahan,Female,CSE,Dhaka,20,3.85,92.0,24.0,Yes,65000
15,Nusrat Jahan,Female,CSE,Dhaka,21,3.81,91.0,23.0,Yes,65000

Quick EDA (Exploratory Data Analysis)

In [37]:
df["department"].value_counts()

department
CSE      11
EEE       6
BBA       5
ME        5
Civil     3
Name: count, dtype: int64

Missing values-count them oer column with- isnull(),sum()

In [39]:
df.isnull().sum()

name           0
gender         0
department     0
city           0
age            0
cgpa           2
attendance     1
study_hours    1
scholarship    0
tuition_fee    0
dtype: int64

## Exercises

Use `students.csv`.

1. Load the CSV. Print its `shape`, its column names, and the first 5 rows.
2. Load `students.xlsx` and confirm it has the same shape as the CSV.
3. Run `info()` and `describe()`. Then use `isnull().sum()` — which columns have missing values, and how many?
4. Select only the `name` and `department` columns (first 5 rows).
5. Use `iloc` to get the first 3 rows and the first 4 columns.
6. Filter the students with `cgpa >= 3.8`. Show `name` and `cgpa`.
7. Filter the CSE students who live in Dhaka (two conditions).
8. Filter students who live in Sylhet or Rajshahi, using `isin`.
9. Sort all students by `cgpa` (highest first) and show the top 5 names and cgpa.
10. Show `value_counts()` for `city`, and `nunique()` for `department`.

In [41]:
#1)
df = pd.read_csv("students.csv")
print(df.shape)
print(df.columns)
print(df.head(5))

(30, 11)
Index(['student_id', 'name', 'gender', 'department', 'city', 'age', 'cgpa',
       'attendance', 'study_hours', 'scholarship', 'tuition_fee'],
      dtype='str')
   student_id           name  gender department        city  age  cgpa  \
0           1  Ayesha Rahman  Female        CSE       Dhaka   21  3.92
1           2    Karim Uddin    Male        EEE  Chattogram   22  3.45
2           3    Sadia Islam  Female        CSE      Sylhet   20  3.78
3           4  Tamim Hossain    Male        BBA       Dhaka   23  2.95
4           5   Nabila Akter  Female        CSE    Rajshahi   21  3.66

   attendance  study_hours scholarship  tuition_fee
0        95.0         25.0         Yes        65000
1        80.0         15.0          No        70000
2        88.0         22.0         Yes        65000
3        72.0         10.0          No        55000
4        90.0         20.0         Yes        65000

In [ ]:
#2)
dfx = pd.read_excel("students.xlsx")
print(dfx.shape)

(30, 11)

In [43]:
#3)
print(df[["name","department"]].head())

            name department
0  Ayesha Rahman        CSE
1    Karim Uddin        EEE
2    Sadia Islam        CSE
3  Tamim Hossain        BBA
4   Nabila Akter        CSE

In [44]:
#4)
print(df[["name","department"]].head())

            name department
0  Ayesha Rahman        CSE
1    Karim Uddin        EEE
2    Sadia Islam        CSE
3  Tamim Hossain        BBA
4   Nabila Akter        CSE

In [45]:
#5)
print(df.iloc[0:3,0:4])

   student_id           name  gender department
0           1  Ayesha Rahman  Female        CSE
1           2    Karim Uddin    Male        EEE
2           3    Sadia Islam  Female        CSE

In [46]:
#6)
print(df[df["cgpa"]>=3.8][["name","cgpa"]])

              name  cgpa
0    Ayesha Rahman  3.92
6   Farhana Yasmin  3.88
8    Sumaiya Begum  3.99
14    Nusrat Jahan  3.81
20   Sharmin Akter  3.95
25    Ishrat Jahan  3.85

In [47]:
#7)
print(df[(df["department"]=="CSE")&(df["city"]=="Dhaka")])

    student_id           name  gender department   city  age  cgpa  \
0            1  Ayesha Rahman  Female        CSE  Dhaka   21  3.92
8            9  Sumaiya Begum  Female        CSE  Dhaka   19  3.99
14          15   Nusrat Jahan  Female        CSE  Dhaka   21  3.81
17          18   Sabbir Ahmed    Male        CSE  Dhaka   23   NaN
25          26   Ishrat Jahan  Female        CSE  Dhaka   20  3.85
28          29   Tanvir Ahmed    Male        CSE  Dhaka   22  3.58

    attendance  study_hours scholarship  tuition_fee
0         95.0         25.0         Yes        65000
8         98.0         28.0         Yes        65000
14        91.0         23.0         Yes        65000
17        66.0          9.0          No        65000
25        92.0         24.0         Yes        65000
28        86.0         19.0          No        65000

In [48]:
#8)
print(df[df["city"].isin(["sylhet","rajshahi"])][["name","city"]])

Empty DataFrame
Columns: [name, city]
Index: []

In [49]:
#9)
print(df.sort_values("cgpa", ascending=False)[["name", "cgpa"]].head(5))

              name  cgpa
8    Sumaiya Begum  3.99
20   Sharmin Akter  3.95
0    Ayesha Rahman  3.92
6   Farhana Yasmin  3.88
25    Ishrat Jahan  3.85

In [50]:
#10)
print(df["city"].value_counts())
print(df["department"].nunique())   # 5

city
Dhaka         11
Chattogram     5
Sylhet         4
Rajshahi       4
Khulna         4
Barishal       2
Name: count, dtype: int64
5